[__ge__]
func = "le"

[__gt__]
func = "lt"

[__radd__]
func = "add"

[__rand__]
func = "and_"

[__rdivmod__]
func = "divmod"
isbuiltin = true

[__rfloordiv__]
func = "floordiv"

[__rlshift__]
func = "lshift"

[__rmatmul__]
func = "matmul"

[__rmod__]
func = "mod"

[__rmul__]
func = "mul"

[__ror__]
func = "or_"

[__rpow__]
func = "pow"

[__rrshift__]
func = "rshift"

[__rsub__]
func = "sub"

[__rtruediv__]
func = "truediv"

[__rxor__]
func = "xor"
